# url: https://uclatall.github.io
# baseurl: /TALL

# Site settings
title: UCLA Teaching and Learning Lab
email: ucla.tall@gmail.com
description: "We are interested in teaching and learning. We are both teachers and learners."



# Members
members:
  - name: Jim Stigler
    pic: Jim.jpg
    email: stigler@ucla.edu 
    intro: Jim Stigler is professor of psychology at UCLA. His research interests include teaching and learning in complex domains, the impacts of culture and technology on learning, and applications of improvement science to education.  

  - name: Karen Givvin
    pic: Karen.jpg
    email: kbgivvin@g.ucla.edu
    intro: Karen Givvin is a researcher and adjunct professor of psychology at UCLA. Her research interests center on teaching, learning, and motivation in achievement domains. <br><br>

  - name: Ji Son
    pic: Ji.jpg
    email: jiyunson@gmail.com
    intro: Ji Son is professor of psychology at Cal State LA. She is interested in how basic cognitive and perceptual processes foster rich and transferable learning. <br><br><br>
    
  - name: Adam Blake
    pic: Adam.jpg
    email: adamblake@ucla.edu
    intro: Adam Blake is a Research Scientist at UCLA. He is interested in the factors that influence students' judgments, decisions, and strategies related to learning, and how instruction and learning materials can improve these behaviors. 

  - name: Laura Fries
    pic: Laura.jpg
    email: lauracfries@gmail.com
    intro: Laura Fries is a graduate student in Developmental Psychology at UCLA. She is interested in the cognitive and affective factors that influence learning, and instructional strategies to promote transferable understanding and retention of complex domains. 
    
  - name: Mary Tucker
    pic: Mary.jpg
    email: maryctucker@ucla.edu
    intro: Mary Tucker is a graduate student in Developmental Psychology at UCLA. Her research interests include the psychological and contextual factors that influence teaching and learning, the design of learning environments in STEM domains, and the application of technology and data analytics to understand and improve teaching and learning.
    
 
  - name: Caylor Davis
    pic: Caylor.jpg
    email: crdavis25@ucla.edu
    intro: Caylor Davis is a researcher and curriculum developer for high school and college statistics courses. She is interested in research and course design that makes math more accessible for non-STEM students. </br> </br>

  - name: Icy (Yunyi) Zhang
    pic: Icy.jpg
    email: yunyi9847@g.ucla.edu
    intro: Icy Zhang is a graduate student in Developmental Psychology at UCLA. She is interested in the role of gesture in supporting students’ understanding of difficult content such as statistics, the application of technology in education, and collaborative learning. 
    
  - name: Claudia Sutter
    pic: Claudia.jpg
    email: ccs3z@virginia.edu
    intro: Claudia C. Sutter is a postdoctoral scholar at UCLA and visiting scholar at UVA. She is interested in understanding (a) what drives students to learn and engage within the educational setting, (b) how students’ motivation (e.g., their beliefs and values) affects their learning behaviors and outcomes, and (c) how educational environments (instruction, learning materials) shape students’ opportunities to reach their full potential.

  - name: Ben Winjum
    pic: Ben.jpg
    email: bwinjum@ucla.edu
    intro: Ben Winjum is a staff member in the High Performance Computing group of UCLA’s Institute for Digital Research and Education, where he works on advanced computing and data analytics projects that support both education and research. </br> </br>

#Alumni
alumni:
  - name: Stacy Shaw
    pic: Stacy.jpg
    email: stacy.tamsen.shaw@gmail.com
    intro: Stacy Shaw graduated from UCLA in 2020 and is now an Assistant Professor at Worcester Polytechnic Institute in the areas of Learning Science and Technology and Psychological and Cognitive Science. Her research focuses on learning in mathematics and statistics with a focus on flexible thinking and creativity. 
  
  - name: Emma Geller
    pic: Emma.jpg
    email: egeller@ucsd.edu
    intro: Emma Geller is an assistant teaching professor at UC San Diego. She is interested in applications of cognitive psychology to support deep learning and understanding in multimedia environments, especially regarding the design of online video learning.


# Papers in publication
# the doi field is optional
# papers should be placed in the pdfs folder
papers:
  - name: The ​Better Book​ Approach for Education Research and Development
    authors: James W. Stigler, Ji Y. Son, Karen B. Givvin, Adam Blake, Laura Fries, Stacy T. Shaw, & Mary C. Tucker
    journal: PREPRINT
    year: 2019
    filename: The “Better Book” Approach for Education.pdf
    abstract: This paper describes a new approach for education research and development - the better book approach - and reports on our initial development and application of the approach in the context of introductory college-level statistics.
    
  - name: "Modeling First: Applying Learning Science to the Teaching of Introductory Statistics"
    authors: Ji Y. Son, Adam Blake, Laura Fries, James W. Stigler
    journal: Journal of Statistics Education
    year: 2021
    filename: Modeling First Applying Learning Science to the Teaching of Introductory Statistics.pdf
    abstract: In this article we describe our attempt to apply theories and findings from learning science to the design of a statistics course that aims to help students build a coherent and interconnected representation of the domain. The resulting practicing connections approach provides students with repeated opportunities to practice connections between core concepts (especially the concepts of statistical model, distribution, and randomness), key representations (R programming language and computational techniques such as simulation and bootstrapping), and real-world situations statisticians face as they explore variation, model variation, and evaluate and compare statistical models. We provide a guided tour through our curriculum implemented in an interactive online textbook (CourseKata.org) and then provide some evidence that students who complete the course are able to transfer what they have learned to the learning of new statistical techniques.

  - name: "Instructed Hand Movements Affect Students’ Learning of an Abstract Concept from Video"
    authors: Icy (Yunyi) Zhang, Karen B. Givvin, Jeffrey M. Sipple, Ji Y. Son,  James W. Stigler
    journal: Cognitive Science
    year: 2021
    filename: Zhang 2021 Instructed hand movements.pdf
    abstract: The two studies reported here investigate the impact of instructed hand movements on students’ subsequent understanding of a concept. Students were asked to watch an instructional video—focused on the concept of statistical model—three times. These two studies found that instructed hand movement—even when presented as an unrelated, secondary task—can affect students’ learning of a complex concept. <a href="https://www.scientificamerican.com/article/students-who-gesture-during-learning-grasp-concepts-better/"> This article was featured in Scientific American.</a>
    
  - name: "Practicing Connections: A Framework to Guide Instructional Design for Developing Understanding in Complex Domains"
    authors: Laura Fries, Ji Y. Son, Karen B. Givvin, James W. Stigler
    journal: Educational Psychology Review
    year: 2020
    filename: 2020 Practicing Connections.pdf
    abstract: "Research suggests that expert understanding is characterized by coherent mental representations featuring a high level of connectedness. This paper advances the idea that educators can facilitate this level of understanding in students through the practicing connections framework: a practical framework to guide instructional design for developing deep understanding and transferable knowledge in complex academic domains." 
    
  - name: Removing Opportunities to Calculate Improves Students’ Performance on Subsequent Word Problems
    authors: Karen B. Givvin, Veronika Moroz, William Loftus, & James W. Stigler
    journal: "Cognitive Research: Principles and Implications"
    year: 2019
    filename: Givvin_et_al-2019-Cognitive_Research__Principles_and_Implications.pdf
    abstract: This paper reports our investigation on whether removing opportunities to calculate could improve students’ subsequent ability to solve similar word problems

  - name: "Exploring the Practicing-connections Hypothesis: Using Gesture to Support Coordination of Ideas in Understanding a Complex Statistical Concept"
    authors: Ji Y. Son , Priscilla Ramos , Melissa DeWolf , William Loftus and James W. Stigler
    journal: "Cognitive Research: Principles and Implications"
    year: 2018
    filename: Practicing connections with gesture.pdf
    abstract: "This paper presented a framework and approach for studying how students come to understand complex concepts in rich domains. Specifically, it explores the role that a teacher’s gesture might play in supporting students’ coordination of two concepts central to understanding in the domain of statistics: mean and standard deviation."
    
  - name: Expertise and Expert Performance in Teaching
    authors: James W. Stigler and Kevin F. Miller
    journal: 
    year: 2018
    filename: Expertise in teaching.pdf
    abstract: This chapter tries to take a broader approach to understanding the nature and development of expertise and expert performance in teaching. The paper also tries to integrate a number of ideas and findings from literatures as diverse as cross-cultural compar- isons of teaching, cognitive psychology, and systems improvement, among others.
    
  - name: DOES VAM + MET = IMPROVED TEACHING?
    authors: James W. Stigler, James Hiebert, and Karen B. Givvin
    journal: 
    year: 2018
    filename: VAM plus MET.pdf
    abstract: The paper discusses the logic of the more traditional approach on which many current policies for improving teaching in the United States are based and then presents an alternative research approach, in which a different theory of improvement is assumed. 
    
  
  - name: Online Learning as a Wind Tunnel for Improving Teaching
    authors: James W. Stigler, Karen B. Givvin
    year: 2017
    filename: Online Learning as a Wind Tunnel for Improving Teaching.pdf
    abstract: The chapter proposes an approach that combines the affordances of online learning with the methodologies of systems improvement. It discusses how online learning might be a wind tunnel for the study and improvement of teaching.
    
    
  - name: "What Community College Developmental Mathematics Students Understand about Mathematics, Part2: The Interviews"
    authors: Karen B. Givvin, James W. Stigler, and Belinda J. Thompson
    journal: 
    year: 2011
    filename: What community college students understand, Part2.pdf
    abstract: Following the prior paper, this article presents findings from one-on-one interviews with a sample of community college developmental math students. These interviews were designed to further probe students’ mathematical thinking, both correct and incorrect.
       
    
  - name: What Community College Developmental Mathematics Students Understand about Mathematics
    authors: James W. Stigler, Karen B. Givvin, and Belinda J. Thompson
    journal: 
    year: 2010
    filename: What community college students know.pdf
    abstract: This paper investigates what community college students actually understand about the mathematics that underlie the topics they’ve been taught and seeks evidence that students used reasoning in answering mathematical questions.
    

# Funders of our projects
funders:
  - name: Chan Zuckerberg Initiative DAF
    pic: Chan.jpg
    
    
  - name: California Governor’s Office of Planning and Research
    pic: Cali_Cov.jpg
    
  - name: Schusterman Foundation
    pic: Schusterman.png


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
