# url: https://uclatall.github.io
# baseurl: /TALL

# Site settings
title: UCLA Teaching and Learning Lab
email: ucla.tall@gmail.com
description: "We are interested in teaching and learning. We are both teachers and learners."



# Members
members:
  - name: Jim Stigler
    pic: Jim.jpg
    email: stigler@ucla.edu 
    intro: Jim Stigler is professor of psychology at UCLA. His research interests include teaching and learning in complex domains, the impacts of culture and technology on learning, and applications of improvement science to education.  

  - name: Karen Givvin
    pic: Karen.jpg
    email: kbgivvin@g.ucla.edu
    intro: Karen Givvin is a researcher and adjunct professor of psychology at UCLA. Her research interests center on teaching, learning, and motivation in achievement domains. <br><br>

  - name: Ji Son
    pic: Ji.jpg
    email: jiyunson@gmail.com
    intro: Ji Son is professor of psychology at CSULA. She is interested in how basic cognitive and perceptual processes foster rich and transferable learning. <br><br><br>
    
  - name: Adam Blake
    pic: Adam.jpg
    email: adamblake@ucla.edu
    intro: Adam Blake is a postdoctoral scholar at UCLA. He is interested in the factors that influence students' judgments, decisions, and strategies related to learning, and how instruction and learning materials can improve these behaviors. 

  - name: Laura Fries
    pic: Laura.jpg
    email: lauracfries@gmail.com
    intro: Laura Fries is a graduate student in Developmental Psychology at UCLA. She is interested in the cognitive and affective factors that influence learning, and instructional strategies to promote transferable understanding and retention of complex domains. 
    
  - name: Mary Tucker
    pic: Mary.jpg
    email: maryctucker@ucla.edu
    intro: Mary Tucker is a graduate student in Developmental Psychology at UCLA. Her research interests include the psychological and contextual factors that influence teaching and learning, the design of learning environments in STEM domains, and the application of technology and data analytics to understand and improve teaching and learning.
    
  - name: Stacy Shaw
    pic: Stacy.jpg
    email: stacy.tamsen.shaw@gmail.com
    intro: Stacy Shaw is a graduate student in Developmental Psychology at UCLA. She is interested in creative thinking in STEM, with an emphasis on how students make connections across concepts, and how affective factors impact students' ability to think flexibly about concepts. 

  - name: Icy (Yunyi) Zhang
    pic: Icy.jpg
    email: zhang_yunyi@outlook.com
    intro: Icy Zhang is a post-baccalaureate research assistant. She is interested in the role of gesture in supporting students’ understanding of difficult content such as statistics, the application of technology in education, and collaborative learning. 



# Papers in publication
# the doi field is optional
# papers should be placed in the pdfs folder
papers:

  - name: Removing Opportunities to Calculate Improves Students’ Performance on Subsequent Word Problems
    authors: Karen B. Givvin, Veronika Moroz, William Loftus, & James W. Stigler
    journal: "Cognitive Research: Principles and Implications"
    year: 2019
    filename: Givvin_et_al-2019-Cognitive_Research__Principles_and_Implications.pdf

  - name: The ​Better Book​ Approach for Education Research and Development
    authors: James W. Stigler, Ji Y. Son, Karen B. Givvin, Adam Blake, Laura Fries, Stacy T. Shaw, & Mary C. Tucker
    journal: PREPRINT
    year: 2019
    filename: The “Better Book” Approach for Education R&D PREPRINT.pdf
    abstract:
    
  - name: Online Learning as a Wind Tunnel for Improving Teaching
    authors: James W. Stigler, Karen B. Givvin
    year: 2017
    filename: Online Learning as a Wind Tunnel for Improving Teaching.pdf
    abstract:
    
  - name: What Community College Developmental Mathematics Students Understand about Mathematics
    authors: James W. Stigler, Karen B. Givvin, and Belinda J. Thompson
    journal: 
    year: 2010
    filename: What community college students know.pdf
    abstract:
    
  - name: What Community College Developmental Mathematics Students Understand about Mathematics (The Interviews)
    authors: James W. Stigler, Karen B. Givvin, and Belinda J. Thompson
    journal: 
    year: 2011
    filename: What community college students understand, Part2.pdf
    abstract: 
    
  - name: "Exploring the Practicing-connections Hypothesis: Using Gesture to Support Coordination of Ideas in Understanding a Complex Statistical Concept"
    authors: Ji Y. Son , Priscilla Ramos , Melissa DeWolf , William Loftus and James W. Stigler
    journal: "Cognitive Research: Principles and Implications"
    year: 2018
    filename: Practicing connections with gesture.pdf
    abstract:
    
  - name: Expertise and Expert Performance in Teaching
    authors: James W. Stigler and Kevin F. Miller
    journal: 
    year: 2018
    filename: Expertise in teaching.pdf
    abstract:     
    
  - name: DOES VAM + MET = IMPROVED TEACHING?
    authors: James W. Stigler, James Hiebert, and Karen B. Givvin
    journal: 
    year: 2018
    filename: VAM plus MET.pdf
    abstract:  
    
    
# Funders of our projects
funders:
  - name: Chan Zuckerberg Initiative DAF
    pic: Chan.jpg
    
    
  - name: California Governor’s Office of Planning and Research
    pic: Cali_Cov.jpg


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty